### ISSUE TITLE
測試

### ISSUE THREAD

**Issue by DF-wu** [DF-wu/RabbitMQ_test#1]
測試trello 連結

**Comment by DF-wu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/S9YeilyH/286-test)

**Comment by DF-wu** [comment]
我覺得你很爛 QQ

**Comment by DF-wu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/S9YeilyH/286-test)

**Comment by stanley2058** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/S9YeilyH/286-test)

**Comment by stanley2058** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/S9YeilyH/286-test)
